"""
ForgePack Video Processor

FFmpeg pipeline:
  1. Validate input file
  2. Extract poster frame (JPEG) at 1 second mark
  3. Encode MP4 (H.264 + AAC, faststart)
  4. Encode WebM (VP9 + Opus)
  5. Generate VTT placeholder
  6. Package all into ZIP

Progress is tracked via a job dict stored in memory.
In production, consider Redis for multi-worker deployments.
"""

import os
import re
import uuid
import zipfile
import subprocess
import threading
from pathlib import Path
from datetime import datetime

# In-memory job store — sufficient for single-worker Railway deployment
# Keys: job_id → {status, progress, message, output_path, error}
JOBS = {}

ALLOWED_INPUT_EXTENSIONS = {
    '.mov', '.mp4', '.avi', '.mts', '.m2ts',
    '.mkv', '.wmv', '.flv', '.webm', '.m4v',
}


def allowed_video(filename: str) -> bool:
    return Path(filename).suffix.lower() in ALLOWED_INPUT_EXTENSIONS


def run_ffmpeg(cmd: list, job_id: str, stage: str, progress_start: int, progress_end: int) -> bool:
    """
    Run an FFmpeg command and update job progress.
    Returns True on success, False on failure.
    """
    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        )
        _, stderr = proc.communicate()

        if proc.returncode != 0:
            JOBS[job_id]['status']  = 'failed'
            JOBS[job_id]['error']   = f"FFmpeg failed at {stage}: {stderr[-500:]}"
            return False

        JOBS[job_id]['progress'] = progress_end
        JOBS[job_id]['message']  = f"{stage} complete"
        return True

    except FileNotFoundError:
        JOBS[job_id]['status'] = 'failed'
        JOBS[job_id]['error']  = 'FFmpeg not found. Ensure FFmpeg is installed.'
        return False
    except Exception as e:
        JOBS[job_id]['status'] = 'failed'
        JOBS[job_id]['error']  = str(e)
        return False


def get_video_duration(input_path: str) -> float:
    """Return video duration in seconds via ffprobe."""
    try:
        result = subprocess.run([
            'ffprobe', '-v', 'error',
            '-show_entries', 'format=duration',
            '-of', 'default=noprint_wrappers=1:nokey=1',
            input_path,
        ], capture_output=True, text=True, timeout=30)
        return float(result.stdout.strip())
    except Exception:
        return 5.0  # fallback


def check_has_audio(input_path: str) -> bool:
    """Check if video file has an audio stream."""
    try:
        result = subprocess.run([
            'ffprobe', '-v', 'error',
            '-select_streams', 'a',
            '-show_entries', 'stream=codec_type',
            '-of', 'default=noprint_wrappers=1:nokey=1',
            input_path,
        ], capture_output=True, text=True, timeout=30)
        return 'audio' in result.stdout.lower()
    except Exception:
        return False


def generate_vtt_placeholder(base_name: str, has_audio: bool) -> str:
    """
    Generate a VTT placeholder file.
    If no audio detected, notes that captions may not be required.
    """
    note = (
        "No spoken audio detected in this video. "
        "Captions may not be required under WCAG 1.2.2. "
        "Verify with content author."
    ) if not has_audio else (
        "PLACEHOLDER: Replace this file with actual captions. "
        "This video contains audio — captions are required for 508 compliance (WCAG 1.2.2)."
    )

    return f"""WEBVTT
Kind: captions
Language: en

NOTE
Generated by ForgePack
File: {base_name}
{note}

00:00:00.000 --> 00:00:05.000
[Captions not yet available]

"""


def process_video_job(
    job_id: str,
    input_path: str,
    base_name: str,
    output_dir: str,
    preset: dict,
    poster_time: float = 1.0,
):
    """
    Main processing pipeline. Runs in a background thread.
    Updates JOBS[job_id] throughout.
    """
    JOBS[job_id].update({
        'status':   'running',
        'progress': 0,
        'message':  'Starting…',
    })

    input_p    = Path(input_path)
    output_p   = Path(output_dir)
    output_p.mkdir(parents=True, exist_ok=True)

    mp4_path    = str(output_p / f"{base_name}.mp4")
    webm_path   = str(output_p / f"{base_name}.webm")
    poster_path = str(output_p / f"{base_name}.jpg")
    vtt_path    = str(output_p / f"{base_name}.vtt")
    zip_path    = str(output_p / f"{base_name}_forgepack.zip")

    # ── Step 1: Probe ─────────────────────────────────────────
    JOBS[job_id]['message'] = 'Analysing source file…'
    duration  = get_video_duration(str(input_p))
    has_audio = check_has_audio(str(input_p))
    poster_ts = min(poster_time, duration * 0.1)  # 10% into video max
    JOBS[job_id]['progress'] = 5

    # ── Step 2: Poster frame ──────────────────────────────────
    JOBS[job_id]['message'] = 'Extracting poster frame…'
    poster_cmd = [
        'ffmpeg', '-y',
        '-ss', str(poster_ts),
        '-i', str(input_p),
        '-frames:v', '1',
        '-q:v', '3',
        '-vf', 'scale=-2:1080',
        poster_path,
    ]
    if not run_ffmpeg(poster_cmd, job_id, 'Poster extraction', 5, 15):
        return

    # ── Step 3: MP4 encode ────────────────────────────────────
    JOBS[job_id]['message'] = 'Encoding MP4 (H.264)…'
    mp4_cfg = preset.get('mp4', {})
    mp4_cmd = [
        'ffmpeg', '-y',
        '-i', str(input_p),
        '-vf',       mp4_cfg.get('vf', 'scale=-2:1080'),
        '-c:v',      mp4_cfg.get('vcodec', 'libx264'),
        '-crf',      mp4_cfg.get('crf', '23'),
        '-preset',   mp4_cfg.get('preset', 'slow'),
        '-movflags', mp4_cfg.get('movflags', '+faststart'),
    ]
    if has_audio:
        mp4_cmd += ['-c:a', mp4_cfg.get('acodec', 'aac'), '-b:a', mp4_cfg.get('ab', '128k')]
    else:
        mp4_cmd += ['-an']
    mp4_cmd.append(mp4_path)

    if not run_ffmpeg(mp4_cmd, job_id, 'MP4 encoding', 15, 60):
        return

    # ── Step 4: WebM encode ───────────────────────────────────
    JOBS[job_id]['message'] = 'Encoding WebM (VP9)…'
    webm_cfg = preset.get('webm', {})
    webm_cmd = [
        'ffmpeg', '-y',
        '-i', str(input_p),
        '-vf',   webm_cfg.get('vf', 'scale=-2:1080'),
        '-c:v',  webm_cfg.get('vcodec', 'libvpx-vp9'),
        '-crf',  webm_cfg.get('crf', '33'),
        '-b:v',  webm_cfg.get('b:v', '0'),
        '-pass', '1',
        '-an',
        '-f', 'webm', os.devnull,
    ]
    # Two-pass VP9 for better quality/size
    if not run_ffmpeg(webm_cmd, job_id, 'WebM pass 1', 60, 70):
        return

    webm_cmd2 = [
        'ffmpeg', '-y',
        '-i', str(input_p),
        '-vf',   webm_cfg.get('vf', 'scale=-2:1080'),
        '-c:v',  webm_cfg.get('vcodec', 'libvpx-vp9'),
        '-crf',  webm_cfg.get('crf', '33'),
        '-b:v',  webm_cfg.get('b:v', '0'),
        '-pass', '2',
    ]
    if has_audio:
        webm_cmd2 += ['-c:a', webm_cfg.get('acodec', 'libopus'), '-b:a', webm_cfg.get('ab', '96k')]
    else:
        webm_cmd2 += ['-an']
    webm_cmd2.append(webm_path)

    if not run_ffmpeg(webm_cmd2, job_id, 'WebM pass 2', 70, 85):
        return

    # Clean up VP9 two-pass log files
    for f in ['ffmpeg2pass-0.log', 'ffmpeg2pass-0.log.mbtree']:
        try: os.remove(f)
        except: pass

    # ── Step 5: VTT placeholder ───────────────────────────────
    JOBS[job_id]['message'] = 'Generating caption placeholder…'
    vtt_content = generate_vtt_placeholder(base_name, has_audio)
    Path(vtt_path).write_text(vtt_content, encoding='utf-8')
    JOBS[job_id]['progress'] = 90

    # ── Step 6: Package ZIP ───────────────────────────────────
    JOBS[job_id]['message'] = 'Packaging output…'
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.write(mp4_path,    f"{base_name}.mp4")
        zf.write(webm_path,   f"{base_name}.webm")
        zf.write(poster_path, f"{base_name}.jpg")
        zf.write(vtt_path,    f"{base_name}.vtt")

        # Include a README
        readme = f"""ForgePack Output
================
Source:  {input_p.name}
Preset:  {preset.get('label', 'Custom')}
Created: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
Audio:   {'Yes' if has_audio else 'No audio detected'}

Files:
  {base_name}.mp4   — Primary video (H.264, web-optimized)
  {base_name}.webm  — Fallback video (VP9, for restricted browsers)
  {base_name}.jpg   — Poster/thumbnail image
  {base_name}.vtt   — Caption file {'(placeholder — replace with real captions)' if has_audio else '(placeholder — audio not detected)'}

CourseForge import:
  Drop all four files into a CourseForge Media block.
  Files with the same base name are auto-paired as companions.
  The .vtt file {'must be replaced with real captions before publishing (508 compliance).' if has_audio else 'is a placeholder — verify no spoken content before publishing.'}
"""
        zf.writestr('README.txt', readme)

    # ── Clean up source + intermediates ──────────────────────
    for path in [mp4_path, webm_path, poster_path, vtt_path]:
        try: os.remove(path)
        except: pass
    try: os.remove(str(input_p))
    except: pass

    JOBS[job_id].update({
        'status':      'complete',
        'progress':    100,
        'message':     'Done',
        'output_path': zip_path,
        'base_name':   base_name,
        'has_audio':   has_audio,
    })


def start_job(input_path: str, base_name: str, output_dir: str, preset: dict) -> str:
    """
    Start a background processing job. Returns job_id.
    """
    job_id = str(uuid.uuid4())
    JOBS[job_id] = {
        'status':      'queued',
        'progress':    0,
        'message':     'Queued',
        'output_path': None,
        'error':       None,
        'created_at':  datetime.utcnow().isoformat(),
    }
    thread = threading.Thread(
        target=process_video_job,
        args=(job_id, input_path, base_name, output_dir, preset),
        daemon=True,
    )
    thread.start()
    return job_id


def get_job(job_id: str) -> dict | None:
    return JOBS.get(job_id)
