"""add gui_themes and project theme columns

Revision ID: 3feb0cd5a697
Revises: ae1d29cb711e
Create Date: 2026-06-15 07:04:14.217880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3feb0cd5a697'
down_revision = 'ae1d29cb711e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gui_themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('token_overrides', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('theme_overrides', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'gui_themes', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('theme_overrides')
        batch_op.drop_column('theme_id')

    op.drop_table('gui_themes')
    # ### end Alembic commands ###
