"""add companion_files to media_assets

Revision ID: 44fb3a6b254f
Revises: 3feb0cd5a697
Create Date: 2026-06-15 08:35:48.015709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fb3a6b254f'
down_revision = '3feb0cd5a697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companion_files', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_column('companion_files')

    # ### end Alembic commands ###
